[[redirects]]
  from = "https://wiki.asellus.org/"
  to = "https://asellus.org/wiki/"
  status = 301
  force = true
  
[[redirects]]
  from = "https://asellus.org/wiki"
  to = "https://asellus.org/wiki/"
  status = 301
  force = true